#!/usr/bin/env python

__srcdir__ = 'src/'

import os
import sys
__path__ = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(1, os.path.join(__path__, __srcdir__))

if sys.version_info[0] == 3:
    import you_get
    if __name__ == '__main__':
        you_get.main(repo_path=__path__)
else:
    from you_get.util import log
    log.wtf("""
    [FATAL] Python 3 is required.
    If Python 3 is already installed on your machine, try to run this script using 'python3 you-get'.""")
